#!/bin/bash

set -e


export WARNINGS='-Wall -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations'
gcc -I. $WARNINGS -Wnested-externs -Winline -pedantic -Wno-long-long -g -O2  -o xsoldier main.c  -lSM -lICE -lX11 -lXpm
./xsoldier | ./pysoldier
