#!/usr/bin/python3 

def main():
  import numpy as np
  from cv2 import imshow, waitKey, cvtColor, COLOR_RGB2BGR
  from hashlib import md5,sha1
  from zlib import adler32
  from fileinput import input

  with open("checksums") as f:
    checksums = [ int(line.strip(),16) for line in f ][:1000]

  for  line, checksum in zip(input(),checksums):
     buffer =  bytes.fromhex( line.strip() )
     assert  adler32( buffer ) == checksum
     image = np.frombuffer( buffer,dtype=np.uint8 ).reshape((-1,500,3))
     imshow("",cvtColor(image,  COLOR_RGB2BGR))
     if ord('q')==waitKey(1): return

main()
